# SITE SETUP

# Appearance
appearance:
  mode: light
  color: indigo

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ""
    org_name: ""
    description: "A simple solution to all software reliability issues"
    twitter: "GetResearchDev"
  analytics:
    google_analytics: "G-KRNWDL966P"
    baidu_tongji: ""
    plausible: ""
    fathom: ""
    pirsch: ""
  verification:
    google: ""
    baidu: ""

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    align: "center"
    fixed_to_top: true
    logo:
      text: ""
      # Logo filename in `assets/media/` folder
      filename: "logo.png"
    button:
      enable: true
      text: "Get Started"
      url: "/contact/"
    show_search: true
    show_theme_chooser: true

# Site footer
footer:
  copyright:
    notice: "© {year} Suresta"

# Localization
locale:
  date_format: "Jan 2, 2006"
  time_format: "3:04 PM"
