name = "Suresta - Site Reliability and Assurance as a Service"
license = "MIT"
licenselink = "https://suresta.com/terms"
description = "Suresta | Site Reliability and Assurance as a Service"

homepage = "https://suresta.com/"


# If the theme has a single author
[author]
  name = "Gustavo Rodríguez"
  homepage = "https://suresta.com//"
